apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-hook-{{ .Values.name }}
spec:
  template:
    metadata:
      annotations:
        "helm.sh/hook": post-install
        "helm.sh/hook-weight": "-5"
        "helm.sh/hook-delete-policy": hook-succeeded
    spec:
      containers:
          - name: main
            image: bitnami/kubectl:1.20
            command: ["/bin/sh", "-c"]
            args:
              - |
                #!/bin/sh
                set -eu
                while [ ! $(kubectl get namespace --ignore-not-found {{ .Values.name }} -o jsonpath='{.status.phase}') = "Active" ]; do echo "namespace {{ .Values.name }} is not ready. retrying" && sleep 2; done
      restartPolicy: OnFailure