{{- if .Values.global.limitRanges }}
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: {{ .Values.profile.name }}
spec:
  limits:
  {{- .Values.global.limitRanges | toYaml | nindent 4 }}
{{- end }}
