apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  annotations:
    # This allows the Profile Controller to update namespace labels such as Istio injection et al.
    owner: {{ .Values.email }}
