{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.name }}
{{- if $secret.type }}
type: {{ $secret.type }}
{{- else }}
type: Opaque
{{- end }}
{{- with $secret.data }}
data: {{ toYaml . | nindent 2 }}
{{- end }}
{{- with $secret.stringData }}
stringData: {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}